### ISSUE TITLE
Fails to log to file with DailyRotateFile

### ISSUE THREAD

**Issue by mattberther** [winstonjs/winston-daily-rotate-file#16]
> Originally reported by @Efreak at https://github.com/winstonjs/winston/issues/468

I see that issue was supposedly fixed with the File transport, however I'm having it with DailyRotateFile transport. I'm testing functionality, and it's failing. There's a simple example listed below. For my actual use case, check this trigger for my node-steam-chat-bot.

```
obscured@obscured:~/old-chatbots$ node
> var winston = require('winston');
undefined
> var logger = new winston.Logger;
undefined
> var b = logger.add(winston.transports.DailyRotateFile, { //don't spam me!
... level: "warn",
... colorize: false,
... timestamp: false,
... filename:'bot.corny.log',
... datePattern:"yyyy-MM-dd-m",
... json:false
... });
undefined
> logger.info("test test");
undefined
> obscured@obscured:~/old-chatbots$ ls bot.corny*
ls: cannot access bot.corny*: No such file or directory
obscured@obscured:~/old-chatbots$
```

**Comment by Shulin** [comment]
Not really sure why this is happening, but I'm just now hitting this as well. Can't figure out why my log file isn't getting created.

**Comment by Shulin** [comment]
For me, I switched around my transport creation. If I create a daily-rotate-file transport first, followed by a console transport, my output would never log to a file.  Switching my code so that I create a console transport first, followed by the rotate file, then everything logs to a file just fine.

I'll try to create a small working example and submit it later.

**Comment by mattberther** [comment]
Closing due to lack of response.
