### ISSUE TITLE
File count rotate issue or requirement.

### ISSUE THREAD

**Issue by mattberther** [winstonjs/winston-daily-rotate-file#21]
> Originally reported by @geforcesong at https://github.com/winstonjs/winston/issues/660

Hello Guys,

I am using Winston for logging in my project. There is a requirement for us I don't know how to implement or can you please kindly modify the package to have that feature for us.
The thing is as follows,
when use file rotation and set maxfiles and maxsize, it works but it will add new file count at the end of each log file, which is

when set maxfiles to 5,
access.log, access1.log, access2.log, access3.log, access4.log
then it will keep increasing to,
access1.log, access2.log, access3.log, access4.log, access5.log
then it will keep increasing to,
access2.log, access3.log, access4.log, access5.log, access6.log

This is current behavior, however what we want is that if reach the maxfiles, we should use the first file name instead of increasing the file count all the time.
that is it will always have these files,
access.log, access1.log, access2.log, access3.log, access4.log

when reach the access4.log, then delete the first access.log and create a new access log and log the data in this file.
BTW, i have set the zippedArchive to true, but i didn't see the files got zipped

**Comment by kumar-b** [comment]
Hi @mattberther,

I am trying to understand the requirement. When we reach the access4.log, then we delete the first access.log and create a new access log and log the data in this file. In this way it is difficult to know which is the latest log. Because it can be any one of them.
Log4j defines rotation policy in two ways. This way there is always a consistency that access.log will be the latest log.
[https://logging.apache.org/log4j/2.x/manual/appenders.html#RolloverStrategies](url)

Captured some snapshots from the above link.
![1](https://cloud.githubusercontent.com/assets/4441266/16119256/577866f6-33f8-11e6-8098-4540c77f7d47.PNG)
![2](https://cloud.githubusercontent.com/assets/4441266/16119265/5b31ce68-33f8-11e6-932f-72968c73fd64.PNG)

**Comment by mattberther** [comment]
@kumar-b would be interested in creating a rotate function (with tests) that satisfies the initial screenshot? Basically, the requirement is that access.log is always current and rotated files are in chronological order. Log4J refers to this as the "fixed window" strategy.

Once we have that, Id like to look for the best place to tie in the rotate function -- Ive done some investigation and found that rotation doesn't happen consistently either (especially when the file is buffered) and I think we'll need to do some refactoring to help with that. Isolating the rotate function in a separate class/module would help with this though. 

Thoughts on the rotate api are:

```
function rotate(file, rotateOptions, cb) {
    this.count = rotateOptions.keep; // this comes from options.maxFiles in winston-daily-rotate-file
}
```

**Comment by nayimsust** [comment]
I am facing the same problem which  @geforcesong mentioned. So is there any way to do that in Winton?

**Comment by marchaos** [comment]
+1 for this. It seems that the current behaviour is not what exists in most other logging frameworks. Normally I would expect the latest log file to be "access.log" rather than a log file with a number appended to it.

**Comment by mattberther** [comment]
Resolving #23 will address this issue.
