### ISSUE TITLE
How to disable date pattern?

### ISSUE THREAD

**Issue by patrickjane** [winstonjs/winston-daily-rotate-file#279]
I have this: 

```
      transports.push(new DailyRotateFile({
         filename: '/path/to/app.log',
         level: config.logs.file.level,
         datePattern: null,
         format: winston.format.combine(winston.format.timestamp({format: "YY/MM/DD HH:mm:ss"}), logFormatter),
         maxSize: config.logs.file.maxSize || '1m',
         maxFiles: config.logs.file.history || '14d',
         zippedArchive: true
      }));
```

I tried giving `datePattern` values of `null` or `''`, yet the filename will still be `app.log.2020-06-12`.

Since upon rotation a number is appended *anyway*, and with a timestamp the log file name will be different each day, I want to completely get rid of the date in the filename.

How can I do this?

Fun fact: If I provide `'disable'` as `datePattern` (just a wild guess), the date is still appended, and in addition a weird sub-directory named `app.log.5i57amb6 / 12` is created which contains a file named `20205`.

BTW: It would be nice if the transport didnt create a bounch of hidden json files. This is really unusual for something as common as a log rotation.

**Comment by mattberther** [comment]
This transport is intended to be used to rotate based on some sort of duration, it does not really fit into the requirements for the transport to disable the date pattern.

Regarding your "fun fact", datePattern is a [momentjs format string](https://momentjs.com/docs/#/displaying/format/), so the `d` becomes the day of the week, `i` is not a token and therefore passed through, `s` is the number of seconds, `a` is AM/PM, `b` is not a token and therefore passed through, etc.

Finally, the transport creates the json files to that it can maintain an audit of the files that it created, so that rotation can survive process restarts. It generates the filename based on a hash of the transport options, however, if you wish to  limit the number created to one, you can pass  and `auditFile` option.
