### ISSUE TITLE
Question: Want to skip the audit file that is created by the transport

### ISSUE THREAD

**Issue by Praneethtkonda** [winstonjs/winston-daily-rotate-file#284]
Hi,
   Is there a way to configure to the ```winston.transports.DailyRotateFile``` so that I won't get the audit files for each log file that I create? I tried not setting the field but seems like it got resorted to the default. Any help in this is appreciated.

Thanks

**Comment by mattberther** [comment]
The files are created so the transport can know which files it created, and can therefore remove. 

There isn't a way to disable the generation of this file because it would effectively prevent the transport from doing a proper cleanup of files created by it.

Is there a particular reason you do not desire this file?

**Comment by Praneethtkonda** [comment]
Thanks, for replying I was planning to organize the log files based on a particular folder structure. Apart from logs I find the audit.json created by winston. From you reply I understood the transport internally uses it. I can organize the audit files. No issues.

One quick question why is the %DATE% mandatory in the file_name field? If I don't specify it is getting appended at the end the file name.

**Comment by mattberther** [comment]
@Praneethtkonda the intent of this transport is to provide time-based rotation. In order to do that, the time needs to be included in the filename somewhere.

**Comment by hakunamatata97k** [comment]
@mattberther, recently I started using the lib, and I'm loving it. I just noticed if there are no logs written, i.e. no `logger.info() | .debug() | etc..`  the audit files are created nevertheless thus taking up space and causing more confusion to users. 
I tried the `lazy` option mentioned in [here](https://github.com/winstonjs/winston/blob/master/docs/transports.md#file-transport), but I don't think this works with the `winston-daily-rotate-file`, because it did no noticeable difference to the result. 
I detailed this in this #378. 
Would be happy to hear your input on the matter :)
