### ISSUE TITLE
Error : Digest method not supported while using winston.transports.DailyRotate

### ISSUE THREAD

**Issue by patilms16** [winstonjs/winston-daily-rotate-file#340]
### Environment :
OS : SUSE Linux Enterprise Server 15 SP2
Node: 14.16.0
Express: 4.17.1,
winston: 3.2.1,
winston-daily-rotate-file: 4.4.2

I am using following code :
```javascript
 var transport = new (winston.transports.DailyRotateFile)({
        filename: 'log/server-%DATE%.log',
        datePattern: 'YYYY-MM-DD-HH',
        maxSize: '100m', //100MB
        zippedArchive: true,
        maxFiles: '10',
        frequency: '24h'
    });
```
and getting error from crypto submodule of nodejs as "Digest method not supported" 

Below is actual line which was throwing error from File "FileStreamRotator.js" under node_modules :
crypto.createHash('md5').update(logfile + "LOG_FILE" + time).digest("hex")

Can someone please help to identify the issue here and probable solution?

stack-overflow : https://stackoverflow.com/questions/71552510/error-digest-method-not-supported-while-using-winston-transports-dailyrotate

**Comment by wbt** [comment]
From [createHash docs](https://nodejs.org/api/crypto.html#cryptocreatehashalgorithm-options): 
>On recent releases of OpenSSL, `openssl list -digest-algorithms` (`openssl list-message-digest-algorithms` for older versions of OpenSSL) will display the available digest algorithms.

Can you please run that command on your platform and see if `md5` is in the list?

**Comment by patilms16** [comment]
`md5` is not in the list. Following is the list from `openssl list -digest-algorithms` :
RSA-SHA1 => SHA1
RSA-SHA1-2 => RSA-SHA1
RSA-SHA224 => SHA224
RSA-SHA256 => SHA256
RSA-SHA3-224 => SHA3-224
RSA-SHA3-256 => SHA3-256
RSA-SHA3-384 => SHA3-384
RSA-SHA3-512 => SHA3-512
RSA-SHA384 => SHA384
RSA-SHA512 => SHA512
RSA-SHA512/224 => SHA512-224
RSA-SHA512/256 => SHA512-256
id-rsassa-pkcs1-v1_5-with-sha3-224 => SHA3-224
id-rsassa-pkcs1-v1_5-with-sha3-256 => SHA3-256
id-rsassa-pkcs1-v1_5-with-sha3-384 => SHA3-384
id-rsassa-pkcs1-v1_5-with-sha3-512 => SHA3-512
MD5-SHA1
SHA1
sha1WithRSAEncryption => SHA1
SHA224
sha224WithRSAEncryption => SHA224
SHA256
sha256WithRSAEncryption => SHA256
SHA3-224
SHA3-256
SHA3-384
SHA3-512
SHA384
sha384WithRSAEncryption => SHA384
SHA512
SHA512-224
sha512-224WithRSAEncryption => SHA512-224
SHA512-256
sha512-256WithRSAEncryption => SHA512-256
sha512WithRSAEncryption => SHA512
SHAKE128
SHAKE256
ssl3-sha1 => SHA1

**Comment by wbt** [comment]
This looks like a system configuration issue rather than necessarily a bug in Winston.  There may be some setting on your system that disabled md5 hashing as it's a pretty weak hash. 
I'm generally in favor of moving past md5 because it's relatively easy to find hash collisions, but would want analysis on the potential for breaking existing workflows which might assume the current algorithm.
In any event, the code you are identifying as problematic isn't in this package (Winston) but rather a dependency, so you might find more knowledgeable input about that in the [repo where it's built].

Please note that when posting related questions in multiple places, it is best practice to include cross-links so that those coming after you who might encounter a similar issue can connect through to one where there might've been some progress; I would have expected to see cross links between this and your [Stack Overflow question](https://stackoverflow.com/questions/71552510/error-digest-method-not-supported-while-using-winston-transports-dailyrotate) as well as with any new question you might open in file-stream-rotator.  Splitting the questions without cross-links and filing on the wrong repo makes open-source work harder than it otherwise should be; please be more considerate of this next time.

**Comment by patilms16** [comment]
Thanks a lot @wbt  for providing the information. 
I have updated the cross-links and will make sure to follow this in future!!

**Comment by patilms16** [comment]
@wbt 
In order to resolve this issue, need an update in daily-rotate-file.js to include option _**audit_hash_type**_ 
https://github.com/winstonjs/winston-daily-rotate-file/blob/a4401b7277353e3375669dae35c0da866cb34e4a/daily-rotate-file.js#L94

Please check : https://github.com/rogerc/file-stream-rotator/issues/90

**Comment by wbt** [comment]
Open to PRs.

**Comment by patilms16** [comment]
Created pull request : https://github.com/winstonjs/winston-daily-rotate-file/pull/344 
Please review and let me know in case any issues.

**Comment by patilms16** [comment]
@wbt Could you please verify and merge this request? We have 1 critical issue  need to be fixed immediately.

**Comment by ajayparsana** [comment]
Thanks @patilms16 for the fix. We recently upgraded our system and facing the similar issue. 

@mattberther @indexzero Can you please help with Merging request 344.  This will unblock us and allow to continue using winston daily rotate. 

Appreciate your help.

**Comment by ajayparsana** [comment]
@wbt Thanks for the merge. @mattberther Can you please publish this to npm

**Comment by mattberther** [comment]
Pushed as `winston-daily-rotate-file@4.7.1`.
